allowBuilds:
  '@bazel/concatjs': set this to true or false
  esbuild: set this to true or false
  just-submit: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  simple-git-hooks: set this to true or false
  unrs-resolver: set this to true or false
