export const env = {
    AUTH_KEYCLOAK_ID: process.env.AUTH_KEYCLOAK_ID,
    AUTH_KEYCLOAK_SECRET: process.env.AUTH_KEYCLOAK_SECRET,
    DISCORD_TOKEN: process.env.DISCORD_TOKEN,

    NEXT_PUBLIC_KEYCLOAK_REDIRECT_URI: process.env.NEXT_PUBLIC_KEYCLOAK_REDIRECT_URI,
    NEXT_PUBLIC_AUTH_REALM: process.env.NEXT_PUBLIC_AUTH_REALM,
    NEXT_PUBLIC_CONTAINER_KEYCLOAK_ENDPOINT: process.env.NEXT_PUBLIC_CONTAINER_KEYCLOAK_ENDPOINT,
    NEXT_PUBLIC_LOCAL_KEYCLOAK_URL: process.env.NEXT_PUBLIC_LOCAL_KEYCLOAK_URL,
    NEXT_PUBLIC_UMAMI_WEBSITE_ID: process.env.NEXT_PUBLIC_UMAMI_WEBSITE_ID,
    NEXT_PUBLIC_DISCORD_REDIRECT_URI: process.env.NEXT_PUBLIC_DISCORD_REDIRECT_URI,
    NEXT_PUBLIC_DISCORD_CLIENT_ID: process.env.NEXT_PUBLIC_DISCORD_CLIENT_ID,
    NEXT_PUBLIC_DISCORD_CLIENT_SECRET: process.env.NEXT_PUBLIC_DISCORD_CLIENT_SECRET,

    NEXT_PUBLIC_DRIVE_LINK: process.env.NEXT_PUBLIC_DRIVE_LINK ?? '',
    NEXT_PUBLIC_PAYLOAD_URI: process.env.NEXT_PUBLIC_PAYLOAD_URI ?? '',

    MONGODB_URI: process.env.MONGODB_URI ?? 'mongodb://127.0.0.1:27017/ignite_forum_department',

    REDIS_URI: process.env.REDIS_URI,
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_USER: process.env.SMTP_USER,
    SMTP_PASS: process.env.SMTP_PASS,
    SMTP_EMAIL_ADDRESS: process.env.SMTP_EMAIL_ADDRESS,
    SQUARE_ACCESS_TOKEN: process.env.SQUARE_ACCESS_TOKEN,
};
